# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cgrenier <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/19 12:11:04 by cgrenier          #+#    #+#              #
#    Updated: 2018/08/19 13:01:51 by cgrenier         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

CFLAGS = -Wall -Wextra -Werror

NAME = colle-2

// SRC = source.c

all : $(NAME)

clean :
	rm -f *.o

fclean : clean
	rm -f $(NAME)
